export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const FETCHED_INGREDIENTS = "FETCHED_INGREDIENTS";
export const FETCHED_INGREDIENTS_FAILS = "FETCHED_INGREDIENTS_FAILS";
