export const ADD_INGREDIENT = "ADD_INGREDIENT";
export const REMOVE_INGREDIENT = "REMOVE_INGREDIENT";
export const FETCHED_INGREDIENTS = "FETCHED_INGREDIENTS";
export const FETCHED_INGREDIENTS_FAILS = "FETCHED_INGREDIENTS_FAILS";

export const PURCHASE_SUCCESS = "PURCHASE_SUCCESS";
export const PURCHASE_FAIL = "PURCHASE_FAIL";
export const PURCHASE_START = "PURCHASE_START";
export const PURCHASE_INIT = "PURCHASE_INIT";

export const FETCH_SUCCESS = "FETCH_SUCCESS";
export const FETCH_FAIL = "FETCH_FAIL";
export const FETCH_START = "FETCH_START";
export const FETCH_INIT = "FETCH_INIT";
